Repository codestates-seb/seb39_main_004, pull requests merged in 2022-09, with the labels that each got.

#9 Feat/be/05 image model
  server/mmz/.gitignore
  server/mmz/build.gradle
  server/mmz/gradle/wrapper/gradle-wrapper.jar
  server/mmz/gradle/wrapper/gradle-wrapper.properties
  server/mmz/gradlew
  server/mmz/gradlew.bat
  server/mmz/settings.gradle
  server/mmz/src/main/java/run/ward/mmz/MmzApplication.java
  server/mmz/src/main/java/run/ward/mmz/domain/image/ImageExtension.java
  server/mmz/src/main/java/run/ward/mmz/domain/image/entity/Image.java
  server/mmz/src/main/java/run/ward/mmz/domain/image/repository/ImageRepository.java
  server/mmz/src/main/java/run/ward/mmz/dto/FileDto.java
  server/mmz/src/main/java/run/ward/mmz/handler/exception/ExceptionHandler.java
  server/mmz/src/main/java/run/ward/mmz/handler/file/FileHandler.java
  server/mmz/src/main/java/run/ward/mmz/mapper/ImageMapper.java
  server/mmz/src/main/java/run/ward/mmz/mapper/ImageMapperImpl.java
  server/mmz/src/main/java/run/ward/mmz/service/FileService.java
  server/mmz/src/main/java/run/ward/mmz/service/image/ImageService.java
  server/mmz/src/main/java/run/ward/mmz/service/image/ImageServiceImpl.java
  server/mmz/src/main/java/run/ward/mmz/web/ImageController.java
  server/mmz/src/main/java/run/ward/mmz/web/config/WebMvcConfig.java
  server/mmz/src/main/resources/application-db.properties
  server/mmz/src/main/resources/application-image.properties
  server/mmz/src/main/resources/application.properties
  server/mmz/src/test/java/run/ward/mmz/MmzApplicationTests.java
Labels: ✨feature, 👨‍💻backend

#11 Feat/be/05 image model
  server/mmz/build.gradle
  server/mmz/src/main/java/run/ward/mmz/MmzApplication.java
  server/mmz/src/main/java/run/ward/mmz/domain/image/ImageExtension.java
  server/mmz/src/main/java/run/ward/mmz/domain/image/entity/Image.java
  server/mmz/src/main/java/run/ward/mmz/domain/image/repository/ImageRepository.java
  server/mmz/src/main/java/run/ward/mmz/dto/FileDto.java
  server/mmz/src/main/java/run/ward/mmz/handler/exception/ExceptionHandler.java
  server/mmz/src/main/java/run/ward/mmz/handler/file/FileHandler.java
  server/mmz/src/main/java/run/ward/mmz/mapper/ImageMapper.java
  server/mmz/src/main/java/run/ward/mmz/mapper/ImageMapperImpl.java
  server/mmz/src/main/java/run/ward/mmz/service/FileService.java
  server/mmz/src/main/java/run/ward/mmz/service/image/ImageService.java
  server/mmz/src/main/java/run/ward/mmz/service/image/ImageServiceImpl.java
  server/mmz/src/main/java/run/ward/mmz/web/ImageController.java
  server/mmz/src/main/java/run/ward/mmz/web/config/WebMvcConfig.java
  server/mmz/src/main/resources/application-db.properties
  server/mmz/src/main/resources/application-image.properties
  server/mmz/src/main/resources/application.properties
Labels: ✨feature, 👨‍💻backend

#23 feat: 자동 배포를 위한 pid 이름 설정 #2
  server/.gitignore
  server/src/main/java/run/ward/mmz/MmzApplication.java
Labels: ✔︎pull requests, 💻server, 👨‍💻backend

#25 Feat/be/01 elk logback aop
  server/build.gradle
  server/src/main/java/run/ward/mmz/log/AspectELK.java
  server/src/main/java/run/ward/mmz/log/LogELK.java
  server/src/main/java/run/ward/mmz/log/LogType.java
  server/src/main/java/run/ward/mmz/web/controller/ImageController.java
  server/src/main/java/run/ward/mmz/web/controller/IndexController.java
  server/src/main/resources/logback-spring.xml
Labels: 💻server, 👨‍💻backend, ⚙️chore

#29 Feat/be/27 rest api docs
  server/src/main/java/run/ward/mmz/domain/post/bookmark/Bookmark.java
  server/src/main/java/run/ward/mmz/dto/TestDto.java
  server/src/main/java/run/ward/mmz/dto/account/AccountDto.java
  server/src/main/java/run/ward/mmz/dto/post/BookmarkDto.java
  server/src/main/java/run/ward/mmz/dto/post/DirectionDto.java
  server/src/main/java/run/ward/mmz/dto/post/IngredientDto.java
  server/src/main/java/run/ward/mmz/dto/post/RecipeDto.java
  server/src/main/java/run/ward/mmz/dto/post/ReviewDto.java
  server/src/main/java/run/ward/mmz/dto/post/TagDto.java
  server/src/main/java/run/ward/mmz/log/AspectELK.java
  server/src/main/java/run/ward/mmz/mapper/BaseMapper.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapper.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapperImpl.java
  server/src/main/java/run/ward/mmz/mapper/post/BookmarkMapper.java
  server/src/main/java/run/ward/mmz/mapper/post/BookmarkMapperImpl.java
  server/src/main/java/run/ward/mmz/service/image/ImageServiceImpl.java
  server/src/main/java/run/ward/mmz/web/controller/IndexController.java
  server/src/main/java/run/ward/mmz/web/controller/OAuthController.java
Labels: ✔︎pull requests, 👨‍💻backend

#34 feat: 도메인 주도 개발을 위한 엔티티 수정 #31
  server/src/main/java/run/ward/mmz/domain/account/Account.java
  server/src/main/java/run/ward/mmz/domain/file/File.java
  server/src/main/java/run/ward/mmz/domain/file/Image/DirectionImage.java
  server/src/main/java/run/ward/mmz/domain/file/Image/ImageType.java
  server/src/main/java/run/ward/mmz/domain/file/Image/ThumbNailImage.java
  server/src/main/java/run/ward/mmz/domain/image/Image.java
  server/src/main/java/run/ward/mmz/domain/post/Bookmark.java
  server/src/main/java/run/ward/mmz/domain/post/Direction.java
  server/src/main/java/run/ward/mmz/domain/post/Ingredient.java
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/domain/post/Review.java
  server/src/main/java/run/ward/mmz/domain/post/Tag.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapper.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/FileRepository.java
  server/src/main/java/run/ward/mmz/repository/ImageRepository.java
  server/src/main/java/run/ward/mmz/service/image/ImageServiceImpl.java
Labels: ✔︎pull requests, 👨‍💻backend

#35 Feat/be/27 rest api docs
  server/src/main/java/run/ward/mmz/domain/account/Account.java
  server/src/main/java/run/ward/mmz/domain/file/File.java
  server/src/main/java/run/ward/mmz/domain/file/Image/DirectionImage.java
  server/src/main/java/run/ward/mmz/domain/file/Image/ImageType.java
  server/src/main/java/run/ward/mmz/domain/file/Image/ThumbNailImage.java
  server/src/main/java/run/ward/mmz/domain/image/Image.java
  server/src/main/java/run/ward/mmz/domain/image/ImageRepository.java
  server/src/main/java/run/ward/mmz/domain/post/Bookmark.java
  server/src/main/java/run/ward/mmz/domain/post/Direction.java
  server/src/main/java/run/ward/mmz/domain/post/Ingredient.java
  server/src/main/java/run/ward/mmz/domain/post/LevelType.java
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/domain/post/Review.java
  server/src/main/java/run/ward/mmz/domain/post/Tag.java
  server/src/main/java/run/ward/mmz/domain/post/direction/Direction.java
  server/src/main/java/run/ward/mmz/domain/post/recipe/Recipe.java
  server/src/main/java/run/ward/mmz/domain/subscribe/Subscribe.java
  server/src/main/java/run/ward/mmz/dto/post/BookmarkDto.java
  server/src/main/java/run/ward/mmz/dto/post/RecipeDto.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapper.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapperImpl.java
  server/src/main/java/run/ward/mmz/mapper/post/BookmarkMapper.java
  server/src/main/java/run/ward/mmz/mapper/post/BookmarkMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/BookmarkRepository.java
  server/src/main/java/run/ward/mmz/repository/DirectionRepository.java
  server/src/main/java/run/ward/mmz/repository/FileRepository.java
  server/src/main/java/run/ward/mmz/repository/IngredientRepository.java
  server/src/main/java/run/ward/mmz/repository/RecipeRepository.java
  server/src/main/java/run/ward/mmz/repository/ReviewRepository.java
  server/src/main/java/run/ward/mmz/repository/SubscribeRepository.java
  server/src/main/java/run/ward/mmz/repository/TagRepository.java
  server/src/main/java/run/ward/mmz/service/image/ImageServiceImpl.java
  server/src/main/java/run/ward/mmz/web/controller/PostController.java
  server/src/main/resources/application.properties
Labels: ✔︎pull requests, 👨‍💻backend

#37 feat: 파일 dto 변경 #31
  server/src/main/java/run/ward/mmz/domain/file/File.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapperImpl.java
Labels: ✔︎pull requests, 👨‍💻backend

#36 [FE] 이미지 업로드 테스트 및 구현
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/ImgUploader.tsx
  client/src/index.css
  client/src/pages/Recipe/AddPost.tsx
  client/src/styles/GlobalStyle.ts
  client/tsconfig.json
Labels: 👩‍💻frontend, ✔︎pull requests

#40 [FE] 로그인 및 회원가입 페이지 마크업
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/images/snsLogin/google.png
  client/src/assets/images/snsLogin/kakao.png
  client/src/assets/images/snsLogin/naver.png
  client/src/components/CommonUI/Button.tsx
  client/src/components/CommonUI/InputWithLabel.tsx
  client/src/components/CommonUI/StyledLink.tsx
  client/src/components/CommonUI/index.ts
  client/src/components/Login/LoginForm.tsx
  client/src/components/Login/SNSLogin.tsx
  client/src/components/README.md
  client/src/components/SNSInfo/SNSInfoForm.tsx
  client/src/components/SignUp/SignUpForm.tsx
  client/src/pages/Auth/Login.tsx
  client/src/pages/Auth/SNSInfo.tsx
  client/src/pages/Auth/SignUp.tsx
  client/src/types/index.d.ts
  client/tsconfig.json
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#42 [FE] 공용 componenets 1차
  client/src/App.tsx
  client/src/components/CommonUI/Footer.tsx
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/SortButtons.tsx
  client/src/components/CommonUI/index.ts
  client/src/components/Layout.tsx
  client/src/index.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#44 Feat/be/31 service layer[RE]
  server/build.gradle
  server/src/main/java/run/ward/mmz/domain/post/Bookmark.java
  server/src/main/java/run/ward/mmz/domain/post/LevelType.java
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/dto/post/IngredientDto.java
  server/src/main/java/run/ward/mmz/dto/post/RecipeDto.java
  server/src/main/java/run/ward/mmz/mapper/BaseMapper.java
  server/src/main/java/run/ward/mmz/mapper/post/BookmarkMapper.java
  server/src/main/java/run/ward/mmz/mapper/post/BookmarkMapperImpl.java
  server/src/main/java/run/ward/mmz/mapper/post/RecipeMapper.java
  server/src/main/java/run/ward/mmz/mapper/post/RecipeMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/AccountRepository.java
  server/src/main/java/run/ward/mmz/repository/BookmarkRepository.java
  server/src/main/java/run/ward/mmz/service/AccountService.java
  server/src/main/java/run/ward/mmz/service/CrudService.java
  server/src/main/java/run/ward/mmz/service/FileService.java
  server/src/main/java/run/ward/mmz/service/RecipeService.java
  server/src/main/java/run/ward/mmz/service/RecipeServiceImpl.java
  server/src/main/java/run/ward/mmz/service/image/ImageService.java
  server/src/main/java/run/ward/mmz/service/image/ImageServiceImpl.java
  server/src/main/java/run/ward/mmz/web/controller/BookmarkController.java
  server/src/main/java/run/ward/mmz/web/controller/ImageController.java
  server/src/main/java/run/ward/mmz/web/controller/PostController.java
  server/src/main/java/run/ward/mmz/web/controller/RecipeController.java
  server/src/main/java/run/ward/mmz/web/controller/RecipeSearchController.java
  server/src/main/java/run/ward/mmz/web/controller/TagSearchController.java
  server/src/main/resources/application-image.properties
Labels: ✔︎pull requests, 👨‍💻backend

#47 [FE] 공용 components (tab, 평점별 제외 완료)
  client/package-lock.json
  client/package.json
  client/public/logo.png
  client/public/logo192.png
  client/public/logo512.png
  client/public/logoKorean.png
  client/src/App.tsx
  client/src/components/CommonUI/Footer.tsx
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/SeletButton.tsx
  client/src/components/CommonUI/SortButtons.tsx
  client/src/components/CommonUI/TextareaWithLabel.tsx
  client/src/components/CommonUI/index.ts
  client/src/components/Layout.tsx
  client/src/styles/GlobalStyle.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#48 [FE] 메인 페이지 마크업
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/icons/bread.svg
  client/src/assets/icons/main_dish.svg
  client/src/assets/icons/noodles.svg
  client/src/assets/icons/pot.svg
  client/src/assets/icons/rice.svg
  client/src/assets/icons/right-arrow.png
  client/src/assets/images/main/banner1.png
  client/src/assets/images/main/banner2.png
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/SortButtons.tsx
  client/src/components/CommonUI/Tag.tsx
  client/src/components/CommonUI/index.ts
  client/src/components/Layout.tsx
  client/src/components/Main/Carousel/Carousel.tsx
  client/src/components/Main/Category/CategoryIcon.tsx
  client/src/components/Main/Category/RecipeCategory.tsx
  client/src/components/Main/RecipeItem/RecipeItem.tsx
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/components/Main/index.ts
  client/src/components/Search/SearchBar.tsx
  client/src/components/Search/SearchResultList.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Search/Search.tsx
  client/src/styles/GlobalStyle.ts
  client/src/types/index.d.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#50 [FE] 레시피 등록 페이지 1차 pull requests
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/SeletButton.tsx
  client/src/components/NewRecipe/ImgServerTest.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/TagsMaker.tsx
  client/src/pages/Recipe/AddPost.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#51 feat: 파일 업로드 및 확장자 변경, fileDto, file Entity 수정 #31
  server/src/main/java/run/ward/mmz/domain/file/File.java
  server/src/main/java/run/ward/mmz/dto/FileDto.java
  server/src/main/java/run/ward/mmz/handler/file/FileHandler.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapperImpl.java
Labels: 👨‍💻backend

#52 Feat/be/31 service layer
  server/src/main/java/run/ward/mmz/domain/post/Ingredient.java
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/domain/post/TestRecipe.java
  server/src/main/java/run/ward/mmz/dto/account/AccountDto.java
  server/src/main/java/run/ward/mmz/dto/post/IngredientDto.java
  server/src/main/java/run/ward/mmz/dto/post/RecipeDto.java
  server/src/main/java/run/ward/mmz/mapper/image/ImageMapperImpl.java
  server/src/main/java/run/ward/mmz/mapper/post/RecipeMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/TestRecipeRepository.java
  server/src/main/java/run/ward/mmz/service/ImageService.java
  server/src/main/java/run/ward/mmz/service/RecipeService.java
  server/src/main/java/run/ward/mmz/service/TestRecipeService.java
  server/src/main/java/run/ward/mmz/service/impl/ImageServiceImpl.java
  server/src/main/java/run/ward/mmz/service/impl/RecipeServiceImpl.java
  server/src/main/java/run/ward/mmz/web/controller/ImageController.java
  server/src/main/java/run/ward/mmz/web/controller/IndexController.java
  server/src/main/java/run/ward/mmz/web/controller/RecipeController.java
  server/src/main/resources/appication-db2.properties
  server/src/main/resources/application.properties
Labels: ✔︎pull requests, 👨‍💻backend

#53 [FE] 검색 페이지 마크업 및 CSS
  client/src/components/Search/SearchBar.tsx
  client/src/components/Search/SearchResultList.tsx
  client/src/pages/Search/Search.tsx
  client/src/styles/GlobalStyle.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#56 [FE] 메인 페이지 및 검색 페이지 CSS 레이아웃 수정
  client/src/components/Layout.tsx
  client/src/components/Main/RecipeItem/RecipeItem.tsx
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/components/Search/SearchBar.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Search/Search.tsx
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#58 [FE] 로그인 및 회원가입 페이지 유효성 검사 적용
  client/package-lock.json
  client/package.json
  client/src/components/CommonUI/Button.tsx
  client/src/components/CommonUI/InputWithLabel.tsx
  client/src/components/CommonUI/StyledInput.tsx
  client/src/components/CommonUI/index.ts
  client/src/components/Login/LoginForm.tsx
  client/src/components/SNSInfo/SNSInfoForm.tsx
  client/src/components/SignUp/SignUpForm.tsx
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#60 [FE] 레시피 등록 페이지 2차 pull requests : typescript의 interface, type 분리
  client/src/components/NewRecipe/AddingIngredients.tsx
  client/src/components/NewRecipe/Guide.tsx
  client/src/components/NewRecipe/ImgServerTest.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/components/NewRecipe/indexNewRecipe.ts
  client/src/pages/Recipe/AddPost.tsx
  client/src/ts/interface.ts
  client/src/ts/type.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#73 feat: info Dto 작성 및 response 구현 #31
  server/src/main/java/run/ward/mmz/dto/respones/RecipeInfoDto.java
  server/src/main/java/run/ward/mmz/mapper/post/RecipeMapper.java
  server/src/main/java/run/ward/mmz/mapper/post/impl/RecipeMapperImpl.java
  server/src/main/java/run/ward/mmz/web/controller/v1/RecipeController.java
Labels: ✔︎pull requests, 👨‍💻backend

#76 [FE]게시글 조회 페이지 마크업
  client/src/App.tsx
  client/src/components/RecipeDetail/IngredientItem.tsx
  client/src/components/RecipeDetail/Rating.tsx
  client/src/components/RecipeDetail/RecipeInfo.tsx
  client/src/components/RecipeDetail/RecipeStep.tsx
  client/src/components/RecipeDetail/RepleContainer.tsx
  client/src/components/RecipeDetail/RepleList.tsx
  client/src/components/RecipeDetail/RepleUpload.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/pages/Recipe/PostDetail.tsx
  client/src/pages/Recipe/data.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#81 Feat/be/31 service layer
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/mapper/post/RecipeMapper.java
  server/src/main/java/run/ward/mmz/mapper/post/impl/RecipeMapperImpl.java
  server/src/main/java/run/ward/mmz/mapper/post/impl/ReviewMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/RecipeRepository.java
  server/src/main/java/run/ward/mmz/service/RecipeService.java
  server/src/main/java/run/ward/mmz/service/impl/RecipeServiceImpl.java
  server/src/main/java/run/ward/mmz/web/controller/v1/RecipeController.java
Labels: 🐛bug, ✨feature, 👨‍💻backend

#82 [FE] 레시피 등록 페이지 3차 pull requests
  client/src/components/NewRecipe/AddingIngredients.tsx
  client/src/components/NewRecipe/ImgServerTest.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/IngredientsSet.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/components/NewRecipe/TagsMaker.tsx
  client/src/components/NewRecipe/indexNewRecipe.ts
  client/src/pages/Recipe/AddPost.tsx
  client/src/ts/interface.ts
  client/src/ts/type.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#83 [FE] 검색 페이지 기능 구현
  client/package.json
  client/public/logo2.svg
  client/src/components/CommonUI/Tag.tsx
  client/src/components/Main/RecipeItem/RecipeItem.tsx
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/components/NewRecipe/AddingIngredients.tsx
  client/src/components/NewRecipe/ImgServerTest.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/IngredientsSet.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/components/NewRecipe/TagsMaker.tsx
  client/src/components/Search/SearchBar.tsx
  client/src/components/Search/SearchResultList.tsx
  client/src/pages/Recipe/AddPost.tsx
  client/src/pages/Recipe/PostDetail.tsx
  client/src/pages/Search/Search.tsx
  client/src/types/interface.ts
  client/src/types/type.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#85 feat : 레시피 level 삭제 및 프론트 데이터 확인 #31
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/dto/request/patch/RecipePatchDto.java
  server/src/main/java/run/ward/mmz/dto/request/post/RecipePostDto.java
  server/src/main/java/run/ward/mmz/dto/respones/RecipeResponseDto.java
  server/src/main/java/run/ward/mmz/mapper/post/impl/RecipeMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/RecipeRepository.java
  server/src/main/java/run/ward/mmz/repository/ReviewRepository.java
  server/src/main/java/run/ward/mmz/service/ReviewService.java
  server/src/main/java/run/ward/mmz/service/impl/ReviewServiceImpl.java
  server/src/main/java/run/ward/mmz/web/controller/v1/RecipeController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/ReviewController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/TestController.java
Labels: ✨feature, 👨‍💻backend

#86 Feat/be/31 service layer
  server/src/main/java/run/ward/mmz/service/TagService.java
  server/src/main/java/run/ward/mmz/service/impl/RecipeServiceImpl.java
  server/src/main/java/run/ward/mmz/web/config/WebMvcConfig.java
Labels: 👨‍💻backend

#91 feat : 검색기능 오류 수정 #31
  server/src/main/java/run/ward/mmz/domain/post/Tag.java
  server/src/main/java/run/ward/mmz/service/impl/RecipeServiceImpl.java
  server/src/main/java/run/ward/mmz/service/impl/RecipeTagServiceImpl.java
Labels: ✨feature, 👨‍💻backend

#94 [FE] 메인 페이지 기능 구현
  client/src/components/Main/Category/CategoryIcon.tsx
  client/src/components/Main/Category/RecipeCategory.tsx
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/components/Search/SearchResultList.tsx
  client/src/pages/Main/Main.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✨feature

#95 [FE] 레시피 등록페이지 이벤트 추가 및 서버 요청 테스트 완료
  client/package.json
  client/src/components/NewRecipe/ImgRadio.tsx
  client/src/components/NewRecipe/RadioBtn.tsx
  client/src/components/NewRecipe/TagWithBtn.tsx
  client/src/components/NewRecipe/TagsMaker.tsx
  client/src/components/NewRecipe/indexNewRecipe.ts
  client/src/pages/Recipe/AddPost.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests
