Repository codestates-seb/seb39_main_004, pull requests merged in 2022-10, with the labels that each got.

#102 [FE] 로그인 및 회원가입 기능 구현
  client/package-lock.json
  client/package.json
  client/src/components/Login/LoginForm.tsx
  client/src/components/SignUp/SignUpForm.tsx
  client/src/hooks/README.md
  client/src/hooks/dispatchHook.ts
  client/src/index.tsx
  client/src/redux/slices/README.md
  client/src/redux/slices/userSlice.ts
  client/src/redux/store/README.md
  client/src/redux/store/store.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#103 [FE] 조회페이지 기능 구현 및 마이페이지 마크업(#70)
  client/src/App.tsx
  client/src/assets/icons/bookmark.svg
  client/src/assets/icons/share.svg
  client/src/assets/icons/star.svg
  client/src/assets/icons/view.svg
  client/src/components/Main/RecipeItem/RecipeItem.tsx
  client/src/components/RecipeDetail/CategoryInfo.tsx
  client/src/components/RecipeDetail/IngredientInfo.tsx
  client/src/components/RecipeDetail/RecipeInfo.tsx
  client/src/components/RecipeDetail/RecipeStep.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/Mypage/MyPageBookMark/MyPageBookMark.tsx
  client/src/pages/Mypage/MyPageFreind/MyPageFollow.tsx
  client/src/pages/Mypage/MyPageFreind/MyPageFollowing.tsx
  client/src/pages/Mypage/MyPageRecipe/MyPageRecipe.tsx
  client/src/pages/Mypage/MyPageReview/MyPageReview.tsx
  client/src/pages/Mypage/MyPageUser/MyPageUser.tsx
  client/src/pages/Recipe/PostDetail.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#104 Feat/be/93 oauth2
  server/build.gradle
  server/src/main/java/run/ward/mmz/MmzApplication.java
  server/src/main/java/run/ward/mmz/domain/account/Account.java
  server/src/main/java/run/ward/mmz/domain/account/Provider.java
  server/src/main/java/run/ward/mmz/domain/account/Role.java
  server/src/main/java/run/ward/mmz/domain/auditable/Auditable.java
  server/src/main/java/run/ward/mmz/domain/post/Bookmark.java
  server/src/main/java/run/ward/mmz/dto/auth/OAuthAttributes.java
  server/src/main/java/run/ward/mmz/dto/auth/SessionUser.java
  server/src/main/java/run/ward/mmz/dto/respones/TagResponseDto.java
  server/src/main/java/run/ward/mmz/handler/auth/LoginFailureHandler.java
  server/src/main/java/run/ward/mmz/handler/auth/LoginSuccessHandler.java
  server/src/main/java/run/ward/mmz/handler/log/LogELK.java
  server/src/main/java/run/ward/mmz/log/AspectELK.java
  server/src/main/java/run/ward/mmz/log/LogELK.java
  server/src/main/java/run/ward/mmz/log/LogType.java
  server/src/main/java/run/ward/mmz/mapper/account/AccountMapper.java
  server/src/main/java/run/ward/mmz/mapper/account/AccountMapperImpl.java
  server/src/main/java/run/ward/mmz/mapper/post/impl/RecipeMapperImpl.java
  server/src/main/java/run/ward/mmz/mapper/post/impl/ReviewMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/AccountRepository.java
  server/src/main/java/run/ward/mmz/service/account/impl/AccountServiceImpl.java
  server/src/main/java/run/ward/mmz/web/auth/OAuth2UserServiceImpl.java
  server/src/main/java/run/ward/mmz/web/auth/PrincipalDetails.java
  server/src/main/java/run/ward/mmz/web/config/ObjectMapperConfig.java
  server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AuthController.java
  server/src/main/resources/application-oauth.properties
  server/src/main/resources/application.properties
Labels: ✨feature, 👨‍💻backend

#106 feat : cors 에러 변경.. #83
  server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
  server/src/main/java/run/ward/mmz/web/config/WebMvcConfig.java
Labels: ✔︎pull requests, 👨‍💻backend

#107 feat : 핸들러 페이지 추가 #83
  server/src/main/java/run/ward/mmz/handler/auth/LoginSuccessHandler.java
Labels: ✔︎pull requests, 👨‍💻backend

#110 Feat/be/93 oauth2
  server/src/main/java/run/ward/mmz/domain/account/Account.java
  server/src/main/java/run/ward/mmz/domain/auditable/Auditable.java
  server/src/main/java/run/ward/mmz/dto/auth/OAuthAttributes.java
  server/src/main/java/run/ward/mmz/dto/auth/PrincipalDetails.java
  server/src/main/java/run/ward/mmz/dto/auth/SessionUser.java
  server/src/main/java/run/ward/mmz/handler/auth/LoginUser.java
  server/src/main/java/run/ward/mmz/handler/file/FileHandler.java
  server/src/main/java/run/ward/mmz/mapper/account/AccountMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/AccountRepository.java
  server/src/main/java/run/ward/mmz/service/account/AccountService.java
  server/src/main/java/run/ward/mmz/service/account/AuthService.java
  server/src/main/java/run/ward/mmz/service/account/impl/AccountServiceImpl.java
  server/src/main/java/run/ward/mmz/service/auth/OAuth2UserService.java
  server/src/main/java/run/ward/mmz/service/auth/PrincipalDetailsService.java
  server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/auth/AuthController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/BookmarkController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/ReviewController.java
  server/src/main/resources/application-image.properties
  server/src/main/resources/application-image2.properties
  server/src/main/resources/application.properties
Labels: ✨feature, 👨‍💻backend

#112 feat : 로그아웃 service di추가 #83
  server/src/main/java/run/ward/mmz/handler/auth/CustomLogoutSuccessHandler.java
Labels: ✔︎pull requests, 👨‍💻backend

#113 [FE] 등록페이지에 수정기능 추가 1차
  client/src/App.tsx
  client/src/components/NewRecipe/AddingIngredients.tsx
  client/src/components/NewRecipe/ImgRadio.tsx
  client/src/components/NewRecipe/ImgServerTest.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/IngredientsSet.tsx
  client/src/components/NewRecipe/RadioBtn.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/components/NewRecipe/TagsMaker.tsx
  client/src/components/NewRecipe/buttons/PlusBtn.jsx
  client/src/components/NewRecipe/buttons/RemoveBtn.tsx
  client/src/components/NewRecipe/indexNewRecipe.ts
  client/src/pages/Recipe/AddPost.tsx
  client/src/types/interface.ts
  client/src/types/type.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#114 [FE] 로그아웃 구현 및 로그인 상태에 따른 헤더 아이콘 변경
  client/src/components/CommonUI/Header.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/SignUp/SignUpForm.tsx
  client/src/redux/slices/userSlice.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#116 Feat/be/93 oauth2
  server/src/main/java/run/ward/mmz/domain/account/Account.java
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/domain/post/Tag.java
  server/src/main/java/run/ward/mmz/domain/subscribe/Subscribe.java
  server/src/main/java/run/ward/mmz/dto/respones/AccountInfoDto.java
  server/src/main/java/run/ward/mmz/handler/exception/ExceptionCode.java
  server/src/main/java/run/ward/mmz/handler/file/FileHandler.java
  server/src/main/java/run/ward/mmz/mapper/account/AccountMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/AccountRepository.java
  server/src/main/java/run/ward/mmz/repository/SubscribeRepository.java
  server/src/main/java/run/ward/mmz/service/account/SubscribeService.java
  server/src/main/java/run/ward/mmz/service/account/impl/AccountServiceImpl.java
  server/src/main/java/run/ward/mmz/service/account/impl/SubscribeServiceImpl.java
  server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/SubscribeController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/auth/AuthController.java
Labels: ✔︎pull requests, ✨feature, 👨‍💻backend

#118 [FE] 로그인/회원가입 페이지 CSS, 조회페이지 CSS 수정
  client/src/assets/icons/loginlogo.svg
  client/src/assets/icons/signlogo.svg
  client/src/components/CommonUI/Button.tsx
  client/src/components/CommonUI/StyledInput.tsx
  client/src/components/CommonUI/StyledLink.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Login/SNSLogin.tsx
  client/src/components/RecipeDetail/CategoryInfo.tsx
  client/src/components/RecipeDetail/IngredientInfo.tsx
  client/src/components/RecipeDetail/RecipeStep.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/components/SignUp/SignUpForm.tsx
  client/src/pages/Auth/Login.tsx
  client/src/pages/Auth/SignUp.tsx
  client/src/pages/Recipe/PostDetail.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/TextStyle.ts
  server/src/main/java/run/ward/mmz/domain/account/Account.java
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/domain/post/Tag.java
  server/src/main/java/run/ward/mmz/domain/subscribe/Subscribe.java
  server/src/main/java/run/ward/mmz/dto/respones/AccountInfoDto.java
  server/src/main/java/run/ward/mmz/handler/exception/ExceptionCode.java
  server/src/main/java/run/ward/mmz/handler/file/FileHandler.java
  server/src/main/java/run/ward/mmz/mapper/account/AccountMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/AccountRepository.java
  server/src/main/java/run/ward/mmz/repository/SubscribeRepository.java
  server/src/main/java/run/ward/mmz/service/account/SubscribeService.java
  server/src/main/java/run/ward/mmz/service/account/impl/AccountServiceImpl.java
  server/src/main/java/run/ward/mmz/service/account/impl/SubscribeServiceImpl.java
  server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/SubscribeController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/auth/AuthController.java
Labels: 👩‍💻frontend, ✔︎pull requests

#122 feat : recipe patch dto -> response dto 변경 #93
  server/src/main/java/run/ward/mmz/dto/request/post/patch/RecipePatchDto.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
Labels: ✔︎pull requests, 👨‍💻backend

#123 feat : 프론트엔드 요청으로 인한, 권한 삭제 get Recipe edit page #93
  server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
Labels: ✔︎pull requests, 👨‍💻backend

#124 Feat/be/121 user page
  server/src/main/java/run/ward/mmz/domain/post/Tag.java
  server/src/main/java/run/ward/mmz/mapper/post/impl/RecipeMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/account/AccountRepository.java
  server/src/main/java/run/ward/mmz/repository/account/SubscribeRepository.java
  server/src/main/java/run/ward/mmz/repository/post/BookmarkRepository.java
  server/src/main/java/run/ward/mmz/repository/post/DirectionRepository.java
  server/src/main/java/run/ward/mmz/repository/post/FileRepository.java
  server/src/main/java/run/ward/mmz/repository/post/IngredientRepository.java
  server/src/main/java/run/ward/mmz/repository/post/RecipeRepository.java
  server/src/main/java/run/ward/mmz/repository/post/RecipeTagRepository.java
  server/src/main/java/run/ward/mmz/repository/post/ReviewRepository.java
  server/src/main/java/run/ward/mmz/repository/post/TagRepository.java
  server/src/main/java/run/ward/mmz/service/account/AccountService.java
  server/src/main/java/run/ward/mmz/service/account/impl/AccountServiceImpl.java
  server/src/main/java/run/ward/mmz/service/account/impl/SubscribeServiceImpl.java
  server/src/main/java/run/ward/mmz/service/auth/OAuth2UserService.java
  server/src/main/java/run/ward/mmz/service/auth/PrincipalDetailsService.java
  server/src/main/java/run/ward/mmz/service/post/BookmarkService.java
  server/src/main/java/run/ward/mmz/service/post/impl/BookmarkServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/DirectionServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/ImageServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/IngredientServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/RecipeServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/RecipeTagServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/ReviewServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/TagServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/TestAccountService.java
  server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
Labels: 🛠️fix, 👨‍💻backend

#128 Feat/be/121 user page 업데이트
  server/src/main/java/run/ward/mmz/domain/account/Account.java
  server/src/main/java/run/ward/mmz/dto/common/ResponseDto.java
  server/src/main/java/run/ward/mmz/dto/respones/ReviewResponseDto.java
  server/src/main/java/run/ward/mmz/dto/respones/UserPageDto.java
  server/src/main/java/run/ward/mmz/mapper/post/impl/ReviewMapperImpl.java
  server/src/main/java/run/ward/mmz/repository/post/RecipeRepository.java
  server/src/main/java/run/ward/mmz/service/account/AccountService.java
  server/src/main/java/run/ward/mmz/service/account/impl/AccountServiceImpl.java
  server/src/main/java/run/ward/mmz/service/account/impl/SubscribeServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/BookmarkService.java
  server/src/main/java/run/ward/mmz/service/post/RecipeService.java
  server/src/main/java/run/ward/mmz/service/post/impl/BookmarkServiceImpl.java
  server/src/main/java/run/ward/mmz/service/post/impl/RecipeServiceImpl.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/SubscribeController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/ReviewController.java
Labels: ✨feature, 👨‍💻backend

#130 https 환경에서 로그인 / 로그아웃 정상적으로 동작하지않는 에러 테스트
  server/src/main/java/run/ward/mmz/domain/post/Recipe.java
  server/src/main/java/run/ward/mmz/handler/auth/CustomLoginFailureHandler.java
  server/src/main/java/run/ward/mmz/handler/exception/ExceptionCode.java
  server/src/main/java/run/ward/mmz/handler/exception/GlobalExceptionHandler.java
  server/src/main/java/run/ward/mmz/service/post/impl/BookmarkServiceImpl.java
  server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
Labels: 👨‍💻backend

#129 [FE] 등록페이지 CSS 1차 적용, heade 마크업, CSS 수정
  client/src/assets/images/Recipe/beverageWhite.svg
  client/src/assets/images/Recipe/beverageYellow.svg
  client/src/assets/images/Recipe/defaultIMG.svg
  client/src/assets/images/Recipe/dessertWhite.svg
  client/src/assets/images/Recipe/dessertYellow.svg
  client/src/assets/images/Recipe/ectWhite.svg
  client/src/assets/images/Recipe/ectYellow.svg
  client/src/assets/images/Recipe/noddleWhite.svg
  client/src/assets/images/Recipe/noddleYellow.svg
  client/src/assets/images/Recipe/recipeLogo.svg
  client/src/assets/images/Recipe/riceWhite.svg
  client/src/assets/images/Recipe/riceYellow.svg
  client/src/assets/logos/logo.svg
  client/src/components/CommonUI/Footer.tsx
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/Tag.tsx
  client/src/components/Layout.tsx
  client/src/components/NewRecipe/Guide.tsx
  client/src/components/NewRecipe/ImgRadio.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/IngredientsSet.tsx
  client/src/components/NewRecipe/RadioBtn.tsx
  client/src/components/NewRecipe/RecipeFormStyled.ts
  client/src/components/NewRecipe/RequireMark.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/TagWithBtn.tsx
  client/src/components/NewRecipe/TagsMaker.tsx
  client/src/components/NewRecipe/buttons/PlusBtn.jsx
  client/src/components/NewRecipe/buttons/RemoveBtn.tsx
  client/src/components/NewRecipe/indexNewRecipe.ts
  client/src/pages/Recipe/AddPost.tsx
  client/src/styles/GlobalStyle.ts
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#132 [FE] 메인페이지 북마크 추가, 리스트 CSS 수정
  client/src/assets/icons/bookmark-off.svg
  client/src/assets/icons/bookmark-on.svg
  client/src/assets/icons/hot.svg
  client/src/components/Main/RecipeItem/RecipeItem.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#133 [FE] 로그인 및 회원가입 에러 핸들링
  client/src/App.tsx
  client/src/components/CommonUI/Button.tsx
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/Redirect.tsx
  client/src/components/CommonUI/StyledLink.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Login/SNSLogin.tsx
  client/src/components/RecipeDetail/RepleUpload.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/components/SignUp/SignUpForm.tsx
  client/src/index.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Mypage/MyPage.tsx
  client/src/redux/slices/userSlice.ts
  client/src/redux/store/store.ts
  client/src/styles/GlobalStyle.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#135 [FE] 레시피 추가 페이지 레이아웃 수정
  client/src/components/NewRecipe/IngredientsSet.tsx
  client/src/components/NewRecipe/RecipeFormStyled.ts
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/buttons/RemoveBtn.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#136 Feat/be/121 user page
  server/src/main/java/run/ward/mmz/dto/common/ResponseDto.java
  server/src/main/java/run/ward/mmz/dto/respones/UserPageDto.java
  server/src/main/java/run/ward/mmz/service/account/SubscribeService.java
  server/src/main/java/run/ward/mmz/service/account/impl/SubscribeServiceImpl.java
  server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java
Labels: ✨feature, 👨‍💻backend

#138 [FE] 북마크 기능 추가
  client/src/components/Main/RecipeItem/RecipeItem.tsx
  client/src/components/RecipeDetail/CategoryInfo.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#139 [FE] 레시피 조회 페이지 수정
  client/src/assets/icons/star.svg
  client/src/components/CommonUI/PostTag.tsx
  client/src/components/CommonUI/index.ts
  client/src/components/RecipeDetail/CategoryInfo.tsx
  client/src/components/RecipeDetail/IngredientInfo.tsx
  client/src/components/RecipeDetail/RecipeStep.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/pages/Recipe/PostDetail.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#141 feat : 전체 리스트 북마크 여부 확인 추가
  server/src/main/java/run/ward/mmz/domain/account/Account.java
  server/src/main/java/run/ward/mmz/domain/post/Bookmark.java
  server/src/main/java/run/ward/mmz/dto/respones/AccountInfoDto.java
  server/src/main/java/run/ward/mmz/dto/respones/RecipeInfoDto.java
  server/src/main/java/run/ward/mmz/handler/auth/LoginUser.java
  server/src/main/java/run/ward/mmz/repository/post/BookmarkRepository.java
  server/src/main/java/run/ward/mmz/service/auth/OAuth2UserService.java
  server/src/main/java/run/ward/mmz/service/post/BookmarkService.java
  server/src/main/java/run/ward/mmz/service/post/impl/BookmarkServiceImpl.java
  server/src/main/java/run/ward/mmz/web/config/SwqggerConfig.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
Labels: ✨feature, 👨‍💻backend

#142 [FE] 북마크 기능 추가
  client/src/App.tsx
  client/src/components/CommonUI/Header.tsx
  client/src/components/Main/RecipeItem/RecipeItem.tsx
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/components/RecipeDetail/CategoryInfo.tsx
  client/src/hooks/useMessage.ts
  client/src/pages/Recipe/AddPost.tsx
  client/src/pages/Recipe/PostDetail.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#143 [FE] 마이 페이지 기능 구현
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/Mypage/MyPageBookMark/MyPageBookMark.tsx
  client/src/pages/Mypage/MyPageFreind/MyPageFollow.tsx
  client/src/pages/Mypage/MyPageFreind/MyPageFollowing.tsx
  client/src/pages/Mypage/MyPageRecipe/MyPageRecipe.tsx
  client/src/pages/Mypage/MyPageReview/MyPageReview.tsx
  client/src/pages/Mypage/MyPageUser/MyPageUser.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#145 [FE] 카테고리 아이콘 변경에 따른 정렬 로직 수정
  client/src/components/Main/Category/CategoryIcon.tsx
  client/src/components/Main/Category/RecipeCategory.tsx
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#147 [FE] 비회원 북마크 시 토스트 메시지 뜨지 않는 문제 해결
  client/src/components/Main/RecipeItem/RecipeItem.tsx
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#149 [FE] 반응형 웹페이지 구현
  client/src/components/CommonUI/Footer.tsx
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/SortButtons.tsx
  client/src/components/CommonUI/Tag.tsx
  client/src/components/Layout.tsx
  client/src/components/Main/Category/RecipeCategory.tsx
  client/src/components/Main/RecipeItem/RecipeItem.tsx
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/components/Search/SearchBar.tsx
  client/src/components/Search/SearchResultList.tsx
  client/src/index.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/Mypage/MyPageBookMark/MyPageBookMark.tsx
  client/src/pages/Mypage/MyPageRecipe/MyPageRecipe.tsx
  client/src/pages/Mypage/MyPageUser/MyPageUser.tsx
  client/src/pages/Search/Search.tsx
  client/src/styles/Theme.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#151 [FE] 로그인,회원가입,조회페이지 반응형 구현
  client/src/assets/icons/bookmark.svg
  client/src/assets/icons/main_dish.svg
  client/src/assets/icons/pot.svg
  client/src/assets/images/Recipe/recipeLogo.svg
  client/src/components/CommonUI/Button.tsx
  client/src/components/CommonUI/Footer.tsx
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/PostTag.tsx
  client/src/components/CommonUI/StyledInput.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Login/SNSLogin.tsx
  client/src/components/Main/RecipeItem/RecipeItem.tsx
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/components/RecipeDetail/CategoryInfo.tsx
  client/src/components/RecipeDetail/IngredientInfo.tsx
  client/src/components/RecipeDetail/RecipeStep.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/components/SNSInfo/SNSInfoForm.tsx
  client/src/components/SignUp/SignUpForm.tsx
  client/src/pages/Auth/Login.tsx
  client/src/pages/Auth/SNSInfo.tsx
  client/src/pages/Auth/SignUp.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Recipe/PostDetail.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#152 [FE] 마이페이지 유저 프로필 경로 변경
  client/src/components/RecipeDetail/CategoryInfo.tsx
  client/src/pages/Mypage/MyPageUser/MyPageUser.tsx
  client/src/pages/Recipe/PostDetail.tsx
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#153 [FE] 레시피 페이지 후기 및 평점 기능
  client/src/components/RecipeDetail/Rating.tsx
  client/src/components/RecipeDetail/RepleContainer.tsx
  client/src/components/RecipeDetail/RepleList.tsx
  client/src/components/RecipeDetail/RepleUpload.tsx
  client/src/components/RecipeDetail/SimpleRating.tsx
  client/src/pages/Mypage/MyPageReview/MyPageReview.tsx
  client/src/pages/Recipe/data.ts
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#157 [FE] 레시피 수정페이지 2차
  client/src/components/NewRecipe/AddingIngredients.tsx
  client/src/components/NewRecipe/IngredientsSet.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/pages/Recipe/EditPost.tsx
  client/src/types/interface.ts
  client/src/types/type.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#159 [FE] 레시피 페이지 id 중복으로 인한 버그 해결
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/pages/Recipe/PostDetail.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#164 [FE] 메인 페이지 무한 스크롤 구현
  client/src/assets/logos/logo.svg
  client/src/assets/logos/logo_move.gif
  client/src/components/CommonUI/Header.tsx
  client/src/components/CommonUI/Loading.tsx
  client/src/components/CommonUI/index.ts
  client/src/hooks/infiniteScroll.tsx
  client/src/pages/Main/Main.tsx
  client/src/types/index.d.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#163 [FE] 헤더 로고 변경
  server/src/main/java/run/ward/mmz/web/config/SwqggerConfig.java
  server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java
  server/src/main/resources/application-swagger.properties
  server/src/main/resources/application.properties
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#167 [FE] 버그 해결 및 카카로 로그인 URL 연결
  client/src/components/Login/LoginForm.tsx
  client/src/components/Login/SNSLogin.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/redux/slices/userSlice.ts
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#169 [FE] 반응형 수정 및 탑버튼 기능 구현
  client/src/assets/images/main/topbtn.png
  client/src/components/Login/LoginForm.tsx
  client/src/components/NewRecipe/IngredientsSet.tsx
  client/src/components/NewRecipe/ThumbNailUploader.tsx
  client/src/components/RecipeDetail/IngredientInfo.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Recipe/PostDetail.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#170 [FE] 로딩 컴포넌트 이미지 변경
  client/src/assets/logos/logo_move2.gif
  client/src/components/CommonUI/Loading.tsx
Labels: 👩‍💻frontend, ✔︎pull requests, ✨feature

#173 [FE] 비로그인 상태에서 레시피 조회 페이지 오류 수정
  client/src/components/NewRecipe/ThumbNailUploadeEdit.tsx
  client/src/components/RecipeDetail/IngredientInfo.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#174 [FE] 수정페이지 썸네일 오류 수정
  client/src/components/NewRecipe/ThumbNailUploader.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/pages/Recipe/EditPost.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#176 [FE] 로그인 유저 정보 없을 시 레시피 페이지 렌더링 되지 않는 버그 해결
  client/src/components/RecipeDetail/UserInfo.tsx
Labels: 🐛bug, 👩‍💻frontend, 🛠️fix

#177 [FE] top버튼 모든 페이지에 적용 및 로딩 컴포넌트 적용
  client/src/App.tsx
  client/src/components/CommonUI/Loading.tsx
  client/src/components/Layout.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/ThumbNailUploadeEdit.tsx
  client/src/components/NewRecipe/ThumbNailUploader.tsx
  client/src/pages/Main/Main.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#178 [FE] 카테고리 버그 1차 픽스 테스트 풀리퀘
  client/src/pages/Main/Main.tsx
Labels: 👩‍💻frontend, ✔︎pull requests, 🛠️fix, ✨feature

#182 [FE] 사용하지 않는 코드 삭제
  client/src/pages/Main/Main.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#183 [FE] 수정페이지 누락값 체크 및 로딩 컴포넌트 수정
  client/src/components/CommonUI/Loading.tsx
  client/src/components/NewRecipe/AddingIngredients.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/hooks/useRecipeValidation.tsx
  client/src/pages/Recipe/AddPost.tsx
  client/src/pages/Recipe/EditPost.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#187 Fix/fe/172 main page
  client/src/components/Login/SNSLogin.tsx
  client/src/pages/Main/Main.tsx
  server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
  server/src/main/java/run/ward/mmz/web/controller/v1/post/ReviewController.java
Labels: ✔︎pull requests

#189 [FE] 레시피 수정페이지 입력칸 제거 후 발생하는 오류 수정, 누락값 체크 보완
  client/src/hooks/useRecipeValidation.tsx
  client/src/pages/Recipe/AddPost.tsx
  client/src/pages/Recipe/EditPost.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#190 [FE] 마이페이지 사용자 프로필 변경 기능 추가
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/components/NewRecipe/ThumbNailUploader.tsx
  client/src/pages/Mypage/MyPageUser/MyPageUser.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#193 (FE) 마이페이지 시간데이터 초단위 제거(#192)
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/pages/Mypage/MyPageBookMark/MyPageBookMark.tsx
  client/src/pages/Mypage/MyPageRecipe/MyPageRecipe.tsx
  client/src/pages/Mypage/MyPageReview/MyPageReview.tsx
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#194 [FE] 레시피 수정, SNS 로그인, 마이페이지
  client/src/assets/images/myPage/deleteicon.png
  client/src/assets/images/myPage/emptyLogo.png
  client/src/assets/images/myPage/review.png
  client/src/assets/images/myPage/star.png
  client/src/components/CommonUI/Redirect.tsx
  client/src/components/Login/SNSLogin.tsx
  client/src/components/Main/RecipeItem/RecipeItemList.tsx
  client/src/components/NewRecipe/ImgUploader.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/components/NewRecipe/ThumbNailUploader.tsx
  client/src/components/RecipeDetail/IngredientInfo.tsx
  client/src/components/RecipeDetail/RepleUpload.tsx
  client/src/components/RecipeDetail/UserInfo.tsx
  client/src/components/SNSInfo/SNSInfoForm.tsx
  client/src/hooks/infiniteScroll.tsx
  client/src/hooks/useRecipeValidation.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/Mypage/MyPageBookMark/MyPageBookMark.tsx
  client/src/pages/Mypage/MyPageFreind/MyPageFollow.tsx
  client/src/pages/Mypage/MyPageFreind/MyPageFollowing.tsx
  client/src/pages/Mypage/MyPageRecipe/MyPageRecipe.tsx
  client/src/pages/Mypage/MyPageReview/MyPageReview.tsx
  client/src/pages/Mypage/MyPageUser/MyPageUser.tsx
  client/src/pages/Recipe/AddPost.tsx
  client/src/pages/Recipe/EditPost.tsx
  client/src/pages/Recipe/PostDetail.tsx
  client/src/redux/slices/userSlice.ts
  client/src/types/interface.ts
Labels: 👩‍💻frontend, ✔︎pull requests

#201 fix: 로그인 하지 않았을 때 후기 페이지 렌더링 되지 않는 버그 해결 (#197)
  client/src/components/RecipeDetail/RepleList.tsx
Labels: 👩‍💻frontend, ✔︎pull requests, 🛠️fix

#203 [FE]메타 og 태그 추가
  client/public/favicon.png
  client/public/favicon.svg
  client/public/index.html
  client/public/ogImage.png
Labels: 👩‍💻frontend, ✔︎pull requests

#206 [FE] 레시피 순서 렌더링 오류 수정
  client/src/components/NewRecipe/AddingIngredients.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/hooks/useRecipeJsonDataValidation.ts
  client/src/pages/Recipe/AddPost.tsx
  client/src/pages/Recipe/EditPost.tsx
Labels: 👩‍💻frontend, ✔︎pull requests

#207 [main] 메타 태그 추가 및 레시피 순서 렌더링 오류 수정
  client/public/favicon.png
  client/public/favicon.svg
  client/public/index.html
  client/public/ogImage.png
  client/src/components/NewRecipe/AddingIngredients.tsx
  client/src/components/NewRecipe/StepSet.tsx
  client/src/components/NewRecipe/StepsMaker.tsx
  client/src/hooks/useRecipeJsonDataValidation.ts
  client/src/pages/Recipe/AddPost.tsx
  client/src/pages/Recipe/EditPost.tsx
Labels: 👩‍💻frontend, ✔︎pull requests
